#!/usr/bin/env bash
# Configures an NGINX server with a custom HTTP header
sudo apt-get update
sudo apt-get -y install nginx
sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.bak
header="\t\tadd_header X-Served-By '$HOSTNAME';\n"
sudo sed -i "31i\ $header" /etc/nginx/sites-enabled/default
sudo service nginx reload
sudo service nginx restart
