#!/usr/bin/env bash
# Transfer a file from the client to a server

pathtofile="$1"
ipaddress="$2"
username="$3"
pathsshkey="$4"

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$pathsshkey" "$pathtofile" "$username"@"$ipaddress":~/
fi
