#!/usr/bin/env bash
# Installs NGINX
# NGINX should be listening on port 80
# When requesting a page with curl, it must return a page that contains "Holberton School"

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School for the win!" | sudo tee -a /usr/share/nginx/html/index.html
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "37i\ $redirect" /etc/nginx/sites-available/default
sudo service nginx reload
