#!/usr/bin/env bash
# Redirects to another page when accessing the page /redirect_me
# The redirection is a 301

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School for the win!" | sudo tee /usr/share/nginx/html/index.html
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "37i\ $redirect" /etc/nginx/sites-available/default
sudo service nginx reload
