#!/usr/bin/env bash
# Configures NGINX server to display custom 404 page
# Page contains the text "Ceci n'est pas une page"

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School for the win!" | sudo tee /usr/share/nginx/html/index.html
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "37i\ $redirect" /etc/nginx/sites-available/default
sudo touch /usr/share/nginx/html/404error.html
echo -e "Ceci n'est pas une page\n" | sudo tee -a /usr/share/nginx/html/404error.html
errorpage="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "37i\ $errorpage" /etc/nginx/sites-available/default
sudo service nginx reload
